# RISC Zero Stellar Deployment Configuration
# Managed by scripts/manage.sh — auto-updated after deploy/management operations


[chains.stellar-testnet]
name = "Stellar Testnet"
admin = "GAHL7IXW3QQZ3I6QFF7RCALJ4H2PH2CBLFHXMGID43TREW6ANUKSXGOE"
router = "CBI2UZ3K4HZW2Y3JK5DAXN2BVGCNFZTLUIOQV7JRGAOEMNA4DUZFF4O2"
timelock-controller = "CDN3XR4USW2STQ2VH635W3YNX3YOODTBIR3VPDE7FYQKTKWSKCBZFARX"
timelock-delay = 0

[[chains.stellar-testnet.verifiers]]
name = "groth16-verifier"
version = "3.0.0"
selector = "73c457ba"
verifier = "CC6XUVRVDUA3XS57AUUN4RWM2S7FPFQ6KTZSW6HTEU4ZOFNF3ORNUXUE"
estop = "CBYTHZE3GMCLSYNO27RSMFB5IGESEGUVWDYA3PY3WPCPXLX35BRDIXGH"
unroutable = false

[chains.stellar-mainnet]
name = "Stellar Mainnet"
admin = ""
router = ""
timelock-controller = ""
timelock-delay = 604800
